### ISSUE TITLE
A problem of Running

### ISSUE THREAD

**Issue by knjwhn** [yoosan/sentpair#1]
How can I get this two resources ? 
local emb_vocab = utils.Vocab(emb_prefix .. '.vocab')
local emb_vecs = torch.load(emb_prefix .. '.300d.th')
I've got glove.840B.300d.zip from https://nlp.stanford.edu/projects/glove/,It is a txt directory
What should I do with the txt data?

**Comment by knjwhn** [comment]
In other word, How can I get the file glove.840B.300d.th to run the code ? 
So much Thanks if there are anyone can help me.

**Comment by yoosan** [comment]
Hi,
please consider using this code 
https://github.com/stanfordnlp/treelstm/blob/master/scripts/convert-wordvecs.lua

**Comment by knjwhn** [comment]
Thanks a lot.the model can run now

**Comment by knjwhn** [comment]
Hi,thanks,and there still have another question about the data preprocess,for example,in SICK dataset
a.cparents, a.parents,a.rels,a.toks ,How can we get it?because i want to change my own data into that format. Hope to your apply

**Comment by yoosan** [comment]
Hi,
This project is based on TreeLSTM https://github.com/stanfordnlp/treelstm. If you want to process your data. Consider using https://github.com/stanfordnlp/treelstm/blob/master/scripts/preprocess-sick.py
